name: propresenter_proto_dart
description: A starting point for Dart libraries or applications.
version: 1.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  fixnum: ^1.0.1
  protobuf: ^2.1.0
